FROM node:16 as build

WORKDIR /app

COPY package*.json ./
RUN npm ci --silent
COPY . .

RUN npm run build

FROM nginx:1.16.0-alpine
COPY --from=build /app/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD "nginx" "-g" "daemon off;"