version: "3.8"
services:
  server:
    build: ./server
    container_name: server
    ports:
      - "3001:3001"
  client:
    build: ./client
    container_name: client
    ports: 
      - "3000:3000"

##installazione##
#docker-compose config

#per far partire insieme client e server##
#docker-compose up --build
